version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verdicomply-api
    ports:
      - "8080:8080"
    environment:
      # Configurações para conexão com o Oracle da FIAP
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      - SPRING_DATASOURCE_USERNAME=RM557024
      - SPRING_DATASOURCE_PASSWORD=240200
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      # Configurações adicionais para retry de conexão
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=120000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=2
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=300000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
      - SPRING_PROFILES_ACTIVE=prod
      # Configurações JWT
      - JWT_SECRET=3778214125442A472D4B614E645267556B58703273357638792F423F4528472B
      - JWT_EXPIRATION=86400000
      - JWT_HEADER=Authorization
      - JWT_PREFIX=Bearer
