-- Script de migração adaptado para H2 - V1
-- Criação da tabela NormaAmbiental
CREATE TABLE NORMA_AMBIENTAL (
    ID_NORMA BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_NORMA VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(200),
    ORGAO_FISCALIZADOR VARCHAR(100)
);

-- Criação da tabela Departamento
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME_DEPARTAMENTO VARCHAR(100) NOT NULL
);

-- Criação da tabela Auditoria
CREATE TABLE AUDITORIA (
    ID_AUDITORIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO BIGINT NOT NULL,
    DATA_AUDITORIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    AUDITOR_RESPONSAVEL VARCHAR(100),
    STATUS_AUDITORIA VARCHAR(20),
    CONSTRAINT FK_AUDITORIA_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- Criação da tabela Conformidade
CREATE TABLE CONFORMIDADE (
    ID_CONFORMIDADE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_AUDITORIA BIGINT NOT NULL,
    ID_NORMA BIGINT NOT NULL,
    ESTA_CONFORME CHAR(1) CHECK (ESTA_CONFORME IN ('S', 'N')),
    OBSERVACAO VARCHAR(200),
    CONSTRAINT FK_CONFORMIDADE_AUDITORIA FOREIGN KEY (ID_AUDITORIA) REFERENCES AUDITORIA(ID_AUDITORIA),
    CONSTRAINT FK_CONFORMIDADE_NORMA FOREIGN KEY (ID_NORMA) REFERENCES NORMA_AMBIENTAL(ID_NORMA)
);

-- Criação da tabela Pendencia
CREATE TABLE PENDENCIA (
    ID_PENDENCIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CONFORMIDADE BIGINT NOT NULL,
    DESCRICAO_PENDENCIA VARCHAR(200),
    PRAZO_RESOLUCAO DATE,
    RESOLVIDA CHAR(1) DEFAULT 'N' CHECK (RESOLVIDA IN ('S', 'N')),
    CONSTRAINT FK_PENDENCIA_CONFORMIDADE FOREIGN KEY (ID_CONFORMIDADE) REFERENCES CONFORMIDADE(ID_CONFORMIDADE)
);

-- Criação da tabela LogConformidade
CREATE TABLE LOG_CONFORMIDADE (
    ID_LOG BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CONFORMIDADE BIGINT,
    ACAO VARCHAR(20),
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DETALHES VARCHAR(200)
);
