-- Script para adicionar novas colunas à tabela NORMA_AMBIENTAL
ALTER TABLE NORMA_AMBIENTAL ADD TITULO VARCHAR2(100);
ALTER TABLE NORMA_AMBIENTAL ADD SEVERIDADE VARCHAR2(50);

-- Atualizar registros existentes com valores padrão
UPDATE NORMA_AMBIENTAL SET TITULO = CODIGO_NORMA WHERE TITULO IS NULL;
UPDATE NORMA_AMBIENTAL SET SEVERIDADE = 'MEDIA' WHERE SEVERIDADE IS NULL;

-- Commit das alterações
COMMIT;
