-- Script de criação do schema para testes com H2

-- Criação das tabelas base primeiro (sem dependências)
-- Criação da tabela NormaAmbiental
CREATE TABLE IF NOT EXISTS NORMA_AMBIENTAL (
    ID_NORMA BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_NORMA VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(200),
    ORGAO_FISCALIZADOR VARCHAR(100)
);

-- Criação da tabela Departamento
CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    ID_DEPARTAMENTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME_DEPARTAMENTO VARCHAR(100) NOT NULL
);

-- Criação da tabela de usuários
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL
);

-- Criação das tabelas com dependências nível 1
-- Criação da tabela Auditoria (depende de Departamento)
CREATE TABLE IF NOT EXISTS AUDITORIA (
    ID_AUDITORIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_DEPARTAMENTO BIGINT NOT NULL,
    DATA_AUDITORIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    AUDITOR_RESPONSAVEL VARCHAR(100),
    STATUS_AUDITORIA VARCHAR(20),
    CONSTRAINT FK_AUDITORIA_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- Criação das tabelas com dependências nível 2
-- Criação da tabela Conformidade (depende de Auditoria e NormaAmbiental)
CREATE TABLE IF NOT EXISTS CONFORMIDADE (
    ID_CONFORMIDADE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_AUDITORIA BIGINT NOT NULL,
    ID_NORMA BIGINT NOT NULL,
    ESTA_CONFORME CHAR(1) CHECK (ESTA_CONFORME IN ('S', 'N')),
    OBSERVACAO VARCHAR(200),
    CONSTRAINT FK_CONFORMIDADE_AUDITORIA FOREIGN KEY (ID_AUDITORIA) REFERENCES AUDITORIA(ID_AUDITORIA),
    CONSTRAINT FK_CONFORMIDADE_NORMA FOREIGN KEY (ID_NORMA) REFERENCES NORMA_AMBIENTAL(ID_NORMA)
);

-- Criação das tabelas com dependências nível 3
-- Criação da tabela Pendencia (depende de Conformidade)
CREATE TABLE IF NOT EXISTS PENDENCIA (
    ID_PENDENCIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CONFORMIDADE BIGINT NOT NULL,
    DESCRICAO_PENDENCIA VARCHAR(200),
    PRAZO_RESOLUCAO DATE,
    RESOLVIDA CHAR(1) DEFAULT 'N' CHECK (RESOLVIDA IN ('S', 'N')),
    CONSTRAINT FK_PENDENCIA_CONFORMIDADE FOREIGN KEY (ID_CONFORMIDADE) REFERENCES CONFORMIDADE(ID_CONFORMIDADE)
);

-- Criação das tabelas sem dependências críticas
-- Criação da tabela LogConformidade
CREATE TABLE IF NOT EXISTS LOG_CONFORMIDADE (
    ID_LOG BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CONFORMIDADE BIGINT,
    ACAO VARCHAR(20),
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DETALHES VARCHAR(200)
);
