-- Criação da sequência para NormaAmbiental
CREATE SEQUENCE SEQ_NORMA_AMBIENTAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela NormaAmbiental
CREATE TABLE NORMA_AMBIENTAL (
    ID_NORMA NUMBER PRIMARY KEY,
    CODIGO_NORMA VARCHAR2(20) NOT NULL,
    DESCRICAO VARCHAR2(200),
    ORGAO_FISCALIZADOR VARCHAR2(100)
);

-- Criação da sequência para Departamento
CREATE SEQUENCE SEQ_DEPARTAMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela Departamento
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER PRIMARY KEY,
    NOME_DEPARTAMENTO VARCHAR2(100) NOT NULL
);

-- Criação da sequência para Auditoria
CREATE SEQUENCE SEQ_AUDITORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela Auditoria
CREATE TABLE AUDITORIA (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    ID_DEPARTAMENTO NUMBER NOT NULL,
    DATA_AUDITORIA DATE DEFAULT SYSDATE,
    AUDITOR_RESPONSAVEL VARCHAR2(100),
    STATUS_AUDITORIA VARCHAR2(20),
    CONSTRAINT FK_AUDITORIA_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- Criação da sequência para Conformidade
CREATE SEQUENCE SEQ_CONFORMIDADE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela Conformidade
CREATE TABLE CONFORMIDADE (
    ID_CONFORMIDADE NUMBER PRIMARY KEY,
    ID_AUDITORIA NUMBER NOT NULL,
    ID_NORMA NUMBER NOT NULL,
    ESTA_CONFORME CHAR(1) CHECK (ESTA_CONFORME IN ('S', 'N')),
    OBSERVACAO VARCHAR2(200),
    CONSTRAINT FK_CONFORMIDADE_AUDITORIA FOREIGN KEY (ID_AUDITORIA) REFERENCES AUDITORIA(ID_AUDITORIA),
    CONSTRAINT FK_CONFORMIDADE_NORMA FOREIGN KEY (ID_NORMA) REFERENCES NORMA_AMBIENTAL(ID_NORMA)
);

-- Criação da sequência para Pendencia
CREATE SEQUENCE SEQ_PENDENCIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela Pendencia
CREATE TABLE PENDENCIA (
    ID_PENDENCIA NUMBER PRIMARY KEY,
    ID_CONFORMIDADE NUMBER NOT NULL,
    DESCRICAO_PENDENCIA VARCHAR2(200),
    PRAZO_RESOLUCAO DATE,
    RESOLVIDA CHAR(1) DEFAULT 'N' CHECK (RESOLVIDA IN ('S', 'N')),
    CONSTRAINT FK_PENDENCIA_CONFORMIDADE FOREIGN KEY (ID_CONFORMIDADE) REFERENCES CONFORMIDADE(ID_CONFORMIDADE)
);

-- Criação da sequência para LogConformidade
CREATE SEQUENCE SEQ_LOG_CONFORMIDADE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela LogConformidade
CREATE TABLE LOG_CONFORMIDADE (
    ID_LOG NUMBER PRIMARY KEY,
    ID_CONFORMIDADE NUMBER,
    ACAO VARCHAR2(20),
    DATA_REGISTRO DATE DEFAULT SYSDATE,
    DETALHES VARCHAR2(200)
);
