-- Inserindo dados na tabela NORMA_AMBIENTAL
INSERT INTO NORMA_AMBIENTAL (ID_NORMA, CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES (SEQ_NORMA_AMBIENTAL.NEXTVAL, 'N001', 'Emissão de CO2 controlada', 'IBAMA');

INSERT INTO NORMA_AMBIENTAL (ID_NORMA, CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES (SEQ_NORMA_AMBIENTAL.NEXTVAL, 'N002', 'Descarte correto de resíduos químicos', 'CETESB');

INSERT INTO NORMA_AMBIENTAL (ID_NORMA, CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES (SEQ_NORMA_AMBIENTAL.NEXTVAL, 'N003', 'Uso racional de água', 'ANA');

INSERT INTO NORMA_AMBIENTAL (ID_NORMA, CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES (SEQ_NORMA_AMBIENTAL.NEXTVAL, 'N004', 'Tratamento de efluentes', 'IBAMA');

INSERT INTO NORMA_AMBIENTAL (ID_NORMA, CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES (SEQ_NORMA_AMBIENTAL.NEXTVAL, 'N005', 'Controle de poluição sonora', 'CONAMA');

-- Inserindo dados na tabela DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Manufatura');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Logística');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'TI Sustentável');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Infraestrutura');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Recursos Naturais');

-- Inserindo dados na tabela AUDITORIA
INSERT INTO AUDITORIA (ID_AUDITORIA, ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (SEQ_AUDITORIA.NEXTVAL, 1, TO_DATE('01/10/2024', 'DD/MM/YYYY'), 'Carlos Silva', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_AUDITORIA, ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (SEQ_AUDITORIA.NEXTVAL, 2, TO_DATE('03/10/2024', 'DD/MM/YYYY'), 'Renata Lima', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_AUDITORIA, ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (SEQ_AUDITORIA.NEXTVAL, 3, TO_DATE('05/10/2024', 'DD/MM/YYYY'), 'André Souza', 'PENDENTE');

INSERT INTO AUDITORIA (ID_AUDITORIA, ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (SEQ_AUDITORIA.NEXTVAL, 4, TO_DATE('07/10/2024', 'DD/MM/YYYY'), 'Mariana Costa', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_AUDITORIA, ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (SEQ_AUDITORIA.NEXTVAL, 5, TO_DATE('09/10/2024', 'DD/MM/YYYY'), 'Juliana Lopes', 'CONCLUÍDA');

-- Inserindo dados na tabela CONFORMIDADE
INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 1, 1, 'S', 'Todos os filtros estão dentro do padrão');

INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 1, 2, 'N', 'Resíduos não separados corretamente');

INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 2, 4, 'S', 'Tratamento adequado implementado');

INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 1, 3, 'S', 'Sistema de reuso implementado');

INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 4, 5, 'N', 'Níveis de ruído acima do permitido');

INSERT INTO CONFORMIDADE (ID_CONFORMIDADE, ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (SEQ_CONFORMIDADE.NEXTVAL, 5, 1, 'N', 'Falta de relatório mensal sobre emissões');

-- Inserindo dados na tabela PENDENCIA
INSERT INTO PENDENCIA (ID_PENDENCIA, ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (SEQ_PENDENCIA.NEXTVAL, 2, 'Instalar separadores de resíduos químicos', TO_DATE('15/10/2024', 'DD/MM/YYYY'), 'N');

INSERT INTO PENDENCIA (ID_PENDENCIA, ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (SEQ_PENDENCIA.NEXTVAL, 5, 'Instalar isolamento acústico', TO_DATE('20/10/2024', 'DD/MM/YYYY'), 'N');

INSERT INTO PENDENCIA (ID_PENDENCIA, ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (SEQ_PENDENCIA.NEXTVAL, 3, 'Substituir filtros na chaminé principal', TO_DATE('10/10/2024', 'DD/MM/YYYY'), 'N');
