-- Inserindo dados na tabela NORMA_AMBIENTAL
INSERT INTO NORMA_AMBIENTAL (CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES ('N001', 'Emissão de CO2 controlada', 'IBAMA');

INSERT INTO NORMA_AMBIENTAL (CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES ('N002', 'Descarte correto de resíduos químicos', 'CETESB');

INSERT INTO NORMA_AMBIENTAL (CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES ('N003', 'Uso racional de água', 'ANA');

INSERT INTO NORMA_AMBIENTAL (CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES ('N004', 'Tratamento de efluentes', 'IBAMA');

INSERT INTO NORMA_AMBIENTAL (CODIGO_NORMA, DESCRICAO, ORGAO_FISCALIZADOR)
VALUES ('N005', 'Controle de poluição sonora', 'CONAMA');

-- Inserindo dados na tabela DEPARTAMENTO
INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO)
VALUES ('Manufatura');

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO)
VALUES ('Logística');

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO)
VALUES ('TI Sustentável');

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO)
VALUES ('Infraestrutura');

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO)
VALUES ('Recursos Naturais');

-- Inserindo dados na tabela AUDITORIA
INSERT INTO AUDITORIA (ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (1, TO_DATE('2024-10-01', 'YYYY-MM-DD'), 'Carlos Silva', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (2, TO_DATE('2024-10-03', 'YYYY-MM-DD'), 'Renata Lima', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (3, TO_DATE('2024-10-05', 'YYYY-MM-DD'), 'André Souza', 'PENDENTE');

INSERT INTO AUDITORIA (ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (4, TO_DATE('2024-10-07', 'YYYY-MM-DD'), 'Mariana Costa', 'CONCLUÍDA');

INSERT INTO AUDITORIA (ID_DEPARTAMENTO, DATA_AUDITORIA, AUDITOR_RESPONSAVEL, STATUS_AUDITORIA)
VALUES (5, TO_DATE('2024-10-09', 'YYYY-MM-DD'), 'Juliana Lopes', 'CONCLUÍDA');

-- Inserindo dados na tabela CONFORMIDADE
INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (1, 1, 'S', 'Todos os filtros estão dentro do padrão');

INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (1, 2, 'N', 'Resíduos não separados corretamente');

INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (2, 3, 'S', 'Consumo monitorado via sensores');

INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (3, 4, 'N', 'Sistema de tratamento inoperante');

INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (4, 5, 'S', 'Nível de ruído dentro do aceitável');

INSERT INTO CONFORMIDADE (ID_AUDITORIA, ID_NORMA, ESTA_CONFORME, OBSERVACAO)
VALUES (5, 1, 'N', 'Falta de relatório mensal sobre emissões');

-- Inserindo dados na tabela PENDENCIA
INSERT INTO PENDENCIA (ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (2, 'Separar resíduos químicos e orgânicos corretamente', TO_DATE('2024-11-01', 'YYYY-MM-DD'), 'N');

INSERT INTO PENDENCIA (ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (4, 'Reativar sistema de tratamento de efluentes', TO_DATE('2024-10-20', 'YYYY-MM-DD'), 'N');

INSERT INTO PENDENCIA (ID_CONFORMIDADE, DESCRICAO_PENDENCIA, PRAZO_RESOLUCAO, RESOLVIDA)
VALUES (6, 'Atualizar planilha de emissões mensais', TO_DATE('2024-10-15', 'YYYY-MM-DD'), 'S');
