-- Criação da sequência para Usuarios
CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criação da tabela de usuários
CREATE TABLE USUARIOS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL
);

-- Inserção de usuários iniciais
-- Senhas: admin, gestor, auditor (hash BCrypt)
INSERT INTO USUARIOS (ID, USERNAME, PASSWORD, ROLE)
VALUES (SEQ_USUARIOS.NEXTVAL, 'admin', '$2a$10$0q7ggf7o.o9c7vpk8/IwL.dZR3/l0b5Bos8iYmJFqgJ4EJXCcO1vq', 'ADMIN');

INSERT INTO USUARIOS (ID, USERNAME, PASSWORD, ROLE)
VALUES (SEQ_USUARIOS.NEXTVAL, 'gestor', '$2a$10$ux6T2s/kQl5nTDaZQ2vgHuDaLRyR8x2lQ4MXJMt0xAJGj.yl4I1f.', 'GESTOR');

INSERT INTO USUARIOS (ID, USERNAME, PASSWORD, ROLE)
VALUES (SEQ_USUARIOS.NEXTVAL, 'auditor', '$2a$10$lF.nM/O8SY/3D3xypBkfyO/0wAAA3pFUKrYVe19znRLMxMbBxP1Im', 'AUDITOR');
