-- Script de limpeza robusta para o esquema Oracle
-- Remove todas as tabelas, sequências, views, funções, procedures e triggers
-- Inclui metadados do Flyway para inicialização limpa

-- Dropar tabelas com CASCADE CONSTRAINTS
DROP TABLE PENDENCIA CASCADE CONSTRAINTS;
DROP TABLE CONFORMIDADE CASCADE CONSTRAINTS;
DROP TABLE LOG_CONFORMIDADE CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA CASCADE CONSTRAINTS;
DROP TABLE NORMA_AMBIENTAL CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE flyway_schema_history CASCADE CONSTRAINTS;

-- Dropar sequências
DROP SEQUENCE SEQ_NORMA_AMBIENTAL;
DROP SEQUENCE SEQ_DEPARTAMENTO;
DROP SEQUENCE SEQ_AUDITORIA;
DROP SEQUENCE SEQ_CONFORMIDADE;
DROP SEQUENCE SEQ_PENDENCIA;
DROP SEQUENCE SEQ_LOG_CONFORMIDADE;
