-- Script ultra-simplificado de inicialização do banco de dados
-- Apenas cria as estruturas essenciais para o funcionamento da aplicação

-- Criando sequências
CREATE SEQUENCE SEQ_NORMA_AMBIENTAL START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SEQ_DEPARTAMENTO START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SEQ_AUDITORIA START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SEQ_CONFORMIDADE START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SEQ_PENDENCIA START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SEQ_LOG_CONFORMIDADE START WITH 1 INCREMENT BY 1
/

-- Criar apenas tabelas básicas sem dependências

-- Tabela para usuários do sistema (simplificada)
CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER',
    ATIVO NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
/

-- Inserir dados básicos na tabela USUARIOS
INSERT INTO USUARIOS (USERNAME, EMAIL, PASSWORD, ROLE) 
VALUES ('admin', 'admin@verdicomply.com', '$2a$10$8n2IGBm0zHBYTfLKv3VhPe8bGiM.Ty9P2c.l8vpZLehP4QFcnkojW', 'ADMIN')
/

-- Commit das alterações
COMMIT;
